#!/usr/bin/env python3
"""
upload_photos.py — Upload stock photos to Shutterstock, 500px.com.cn, Tuchong, Adobe Stock, and/or iStock/Getty.

For each image in the target directory, finds its matching JSON metadata file
(generated by photo_desc.py) and automates the upload via Playwright.

Usage:
  python3 upload_photos.py <directory> [--platform shutterstock|px500|tuchong|adobestock|istock|all] [--dry-run]
"""

import argparse
from datetime import datetime, timezone
import json
import sys
from pathlib import Path

from metadata_core import (
    enforce_limits,
    find_batch_quality_issues,
    image_sha256,
    validate_metadata,
    validate_metadata_quality,
)
from visual_facts import (
    normalize_visual_facts,
    validate_metadata_against_visual_facts,
    validate_visual_fact_batch,
    validate_visual_facts,
    visual_facts_sha256,
)
from upload.status import UploadStatus

SUPPORTED_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}
HISTORY_FILENAME = ".stock_upload_history.json"


def find_pairs(directory: Path) -> list[tuple[Path, Path]]:
    """Return exact image/metadata pairs, choosing the newest JSON per source file."""
    images = {
        path.name: path
        for path in directory.iterdir()
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTS
    }
    json_by_source: dict[str, list[tuple[Path, dict]]] = {}
    for json_path in directory.glob("*.json"):
        try:
            metadata = load_metadata(json_path)
        except (OSError, ValueError, json.JSONDecodeError):
            continue
        source = metadata.get("source")
        if isinstance(source, str) and source in images:
            json_by_source.setdefault(source, []).append((json_path, metadata))

    pairs = []
    for source, candidates in json_by_source.items():
        newest_json, _ = max(
            candidates,
            key=lambda item: (
                str(item[1].get("generated_at", "")),
                item[0].stat().st_mtime,
            ),
        )
        pairs.append((images[source], newest_json))
    return sorted(pairs, key=lambda pair: pair[0].name)


def find_images_without_metadata(
    directory: Path,
    pairs: list[tuple[Path, Path]] | None = None,
) -> list[Path]:
    """Return in-scope images that have no exact-source metadata pair."""
    if pairs is None:
        pairs = find_pairs(directory)
    paired_images = {image.resolve() for image, _ in pairs}
    return sorted(
        (
            path
            for path in directory.iterdir()
            if path.is_file()
            and path.suffix.lower() in SUPPORTED_EXTS
            and path.resolve() not in paired_images
        ),
        key=lambda path: path.name,
    )


def load_metadata(json_path: Path) -> dict:
    return json.loads(json_path.read_text(encoding="utf-8"))


def _load_history(directory: Path) -> dict:
    path = directory / HISTORY_FILENAME
    if not path.exists():
        return {"version": 1, "uploads": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data.get("uploads"), dict):
            raise ValueError("missing uploads object")
        return data
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"  [warn] Ignoring invalid upload history: {e}", flush=True)
        return {"version": 1, "uploads": {}}


def _save_history(directory: Path, history: dict) -> None:
    path = directory / HISTORY_FILENAME
    temp_path = path.with_suffix(".tmp")
    temp_path.write_text(
        json.dumps(history, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temp_path.replace(path)


def _image_digest(path: Path) -> str:
    return image_sha256(path)


def _history_entry_completed(entry: object) -> bool:
    """Treat legacy records as complete, but allow uploaded-only work to resume."""
    if not isinstance(entry, dict):
        return True
    value = entry.get("status")
    if value is None:
        return True
    try:
        return UploadStatus(value).completed
    except ValueError:
        return False


def _validate_metadata_binding(
    image: Path,
    metadata: dict,
    allow_unbound: bool,
    allow_unreviewed: bool = False,
    allow_quality_warnings: bool = False,
) -> dict:
    _ = allow_quality_warnings  # retained for CLI compatibility; advisories never block
    if image.stat().st_size <= 0:
        raise ValueError("image file is empty")
    try:
        from PIL import Image
        with Image.open(image) as opened:
            opened.verify()
    except ImportError:
        pass
    except Exception as error:
        raise ValueError(f"image cannot be decoded: {error}")
    source = metadata.get("source")
    if source != image.name:
        raise ValueError(f"metadata source is {source!r}, expected {image.name!r}")
    expected_digest = metadata.get("source_sha256")
    if not expected_digest:
        if not allow_unbound:
            raise ValueError(
                "metadata has no source_sha256; regenerate it or use "
                "--allow-unbound-metadata"
            )
    else:
        actual_digest = _image_digest(image)
        if expected_digest != actual_digest:
            raise ValueError("image content changed after metadata generation")

    normalized = enforce_limits(metadata)
    errors = validate_metadata(normalized) + validate_metadata_quality(normalized)
    visual_facts = metadata.get("visual_facts")
    if (
        metadata.get("visual_review_method") == "agent-native"
        and not isinstance(visual_facts, dict)
    ):
        errors.append(
            "agent-native verified metadata is missing machine-readable visual facts"
        )
    if visual_facts is not None:
        errors += validate_visual_facts(visual_facts)
        errors += validate_metadata_against_visual_facts(normalized, visual_facts)
        expected_facts_digest = metadata.get("visual_facts_sha256")
        if expected_facts_digest != visual_facts_sha256(visual_facts):
            errors.append("visual facts digest does not match the metadata sidecar")
    if errors:
        raise ValueError("; ".join(errors))
    if metadata.get("visual_review_status") != "verified" and not allow_unreviewed:
        raise ValueError(
            "metadata is not visually verified; regenerate/review it or use "
            "--allow-unreviewed-metadata"
        )
    if visual_facts is not None:
        normalized["visual_facts"] = normalize_visual_facts(visual_facts)
        normalized["visual_facts_sha256"] = visual_facts_sha256(visual_facts)
    return normalized


# Max images per single upload session per platform (platform UI limits)
_BATCH_LIMIT = {
    "shutterstock": 100,
    "px500":        100,
    "tuchong":        3,
    "adobestock":    50,
    "istock":        50,
}

_STABLE_PLATFORMS = ("shutterstock", "px500", "tuchong", "adobestock")
_PLATFORM_LABELS = {
    "shutterstock": "Shutterstock",
    "px500": "500px/VCG",
    "tuchong": "Tuchong",
    "adobestock": "Adobe Stock",
    "istock": "Getty/iStock",
}


def _chunked(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i : i + size]


def _run_platform_batch(loaded, batch_fn, limit, label):
    """Call batch_fn in chunks of `limit`, return merged results dict."""
    merged = {}
    chunks = list(_chunked(loaded, limit))
    for idx, chunk in enumerate(chunks, 1):
        if len(chunks) > 1:
            print(f"  [{label}] batch {idx}/{len(chunks)} ({len(chunk)} images)", flush=True)
        merged.update(batch_fn(chunk))
    return merged


def _result_counts(batch_results) -> tuple[int, int]:
    def completed(value):
        return value.completed if isinstance(value, UploadStatus) else bool(value)

    ok = sum(1 for value in batch_results.values() if completed(value))
    return ok, len(batch_results) - ok


def _platform_enabled(requested: str, target: str) -> bool:
    return requested == target or (requested == "all" and target in _STABLE_PLATFORMS)


def run_upload(
    pairs: list[tuple[Path, Path]],
    platform: str,
    *,
    force: bool = False,
    allow_unbound_metadata: bool = False,
    allow_unreviewed_metadata: bool = False,
    allow_quality_warnings: bool = False,
    allow_repeated_metadata: bool = False,
    preserve_all_frames: bool = False,
    repair_corrections: bool = False,
) -> bool:
    from playwright.sync_api import sync_playwright
    import upload.px500 as _px500
    from upload.browser import get_context

    results_by_platform: dict[str, dict[str, UploadStatus]] = {}
    skipped_by_platform: dict[str, int] = {}
    preflight_by_platform: dict[str, dict[str, UploadStatus]] = {}
    history_directory = pairs[0][0].parent
    history = _load_history(history_directory)
    digests = {img.name: _image_digest(img) for img, _ in pairs}

    def prepare(platform_key: str) -> list[tuple[Path, dict]]:
        completed = history["uploads"].get(platform_key, {})
        loaded = []
        skipped = 0
        preflight_results = {}
        for img, json_path in pairs:
            entry = completed.get(digests[img.name])
            if (
                not repair_corrections
                and not force
                and entry is not None
                and _history_entry_completed(entry)
            ):
                skipped += 1
                continue
            try:
                metadata = load_metadata(json_path)
                normalized = _validate_metadata_binding(
                    img,
                    metadata,
                    allow_unbound_metadata,
                    allow_unreviewed_metadata,
                    allow_quality_warnings,
                )
                loaded.append((img, normalized))
            except (OSError, ValueError, json.JSONDecodeError) as error:
                print(f"  [review] {img.name}: {error}", flush=True)
                preflight_results[img.name] = UploadStatus.NEEDS_REVIEW
        fact_batch_issues = validate_visual_fact_batch(
            [
                {
                    "image": image.name,
                    "metadata": metadata,
                    "visual_facts": metadata.get("visual_facts"),
                }
                for image, metadata in loaded
                if metadata.get("visual_facts") is not None
            ],
            require_complete_ranking=False,
            max_selected_per_burst=None if preserve_all_frames else 3,
        )
        if fact_batch_issues:
            facts_loaded = [
                (image, metadata)
                for image, metadata in loaded
                if metadata.get("visual_facts") is not None
            ]
            blocked = set()
            for index, issues in sorted(fact_batch_issues.items()):
                filename = facts_loaded[index - 1][0].name
                blocked.add(filename)
                print(
                    f"  [review] {filename}: " + "; ".join(issues),
                    flush=True,
                )
                preflight_results[filename] = UploadStatus.NEEDS_REVIEW
            loaded = [
                (image, metadata)
                for image, metadata in loaded
                if image.name not in blocked
            ]

        repeated = find_batch_quality_issues(
            [(image.name, metadata) for image, metadata in loaded],
            visual_facts_by_source={
                image.name: metadata["visual_facts"]
                for image, metadata in loaded
                if metadata.get("visual_facts") is not None
            },
            allow_full_coverage_bursts=preserve_all_frames,
        )
        if repeated and not allow_repeated_metadata:
            blocked = set(repeated)
            for filename, issues in sorted(repeated.items()):
                print(
                    f"  [review] {filename}: " + "; ".join(issues),
                    flush=True,
                )
                preflight_results[filename] = UploadStatus.NEEDS_REVIEW
            loaded = [(image, metadata) for image, metadata in loaded if image.name not in blocked]

        skipped_by_platform[platform_key] = skipped
        preflight_by_platform[platform_key] = preflight_results
        if skipped:
            print(f"  [{platform_key}] skipped {skipped} previously completed image(s)", flush=True)
        return loaded

    def record(platform_key: str, batch_results: dict[str, UploadStatus]) -> None:
        completed = history["uploads"].setdefault(platform_key, {})
        changed = False
        for filename, status in batch_results.items():
            if not status.recordable:
                continue
            completed[digests[filename]] = {
                "filename": filename,
                "completed_at": datetime.now(timezone.utc).isoformat(),
                "status": status.value,
            }
            changed = True
        if changed:
            try:
                _save_history(history_directory, history)
            except OSError as e:
                print(f"  [warn] Could not save upload history: {e}", flush=True)

    selected_keys = [
        key for key in _PLATFORM_LABELS if _platform_enabled(platform, key)
    ]
    prepared = {key: prepare(key) for key in selected_keys}
    for key in selected_keys:
        results_by_platform[_PLATFORM_LABELS[key]] = dict(preflight_by_platform[key])

    def execute_platform(key, loaded, context):
        if key == "shutterstock":
            from upload.shutterstock import repair_corrections_batch, upload_batch
            if repair_corrections:
                batch_fn = lambda chunk, browser_context: repair_corrections_batch(
                    chunk, browser_context
                )
            else:
                batch_fn = lambda chunk, browser_context: upload_batch(
                    chunk,
                    browser_context,
                    refresh_metadata=force,
                )
            return _run_platform_batch(
                loaded, lambda chunk: batch_fn(chunk, context),
                _BATCH_LIMIT[key], key,
            )
        if key == "px500":
            _px500.ensure_login(context)
            return _run_platform_batch(
                loaded, lambda chunk: _px500.upload_batch(chunk, context),
                _BATCH_LIMIT[key], key,
            )
        if key == "tuchong":
            import upload.tuchong as adapter
            adapter.ensure_login(context)
        elif key == "adobestock":
            import upload.adobestock as adapter
        else:
            import upload.istock as adapter
            adapter.ensure_login(context)
        return _run_platform_batch(
            loaded, lambda chunk: adapter.upload_batch(chunk, context),
            _BATCH_LIMIT[key], key,
        )

    with sync_playwright() as pw:
        for key in selected_keys:
            loaded = prepared[key]
            if not loaded:
                continue
            context = None
            try:
                context = get_context(key, pw)
                batch_results = execute_platform(key, loaded, context)
            except Exception as error:
                print(f"  [fail] {_PLATFORM_LABELS[key]} aborted: {error}", flush=True)
                batch_results = {
                    image.name: UploadStatus.FAILED for image, _ in loaded
                }
            finally:
                if context is not None:
                    context.close()
            results_by_platform[_PLATFORM_LABELS[key]].update(batch_results)
            record(key, batch_results)

    summary_label = "Correction repair summary" if repair_corrections else "Upload summary"
    print(f"\n{summary_label}:", flush=True)
    platform_keys = {label: key for key, label in _PLATFORM_LABELS.items()}
    for label, batch_results in results_by_platform.items():
        counts = {
            status: sum(1 for value in batch_results.values() if value == status)
            for status in UploadStatus
        }
        details = ", ".join(
            f"{count} {status.value}"
            for status, count in counts.items()
            if count
        ) or "no work"
        skipped = skipped_by_platform.get(platform_keys[label], 0)
        skipped_text = f", {skipped} previously completed" if skipped else ""
        print(
            f"  {label}: {details}{skipped_text}",
            flush=True,
        )
    return all(
        status.completed
        for batch_results in results_by_platform.values()
        for status in batch_results.values()
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Upload stock photos to image platforms")
    parser.add_argument("directory", help="Directory containing images and their JSON metadata")
    parser.add_argument(
        "--platform", "-p",
        choices=["shutterstock", "px500", "tuchong", "adobestock", "istock", "all"],
        default="all",
        help=(
            "Target platform (default: all stable platforms). "
            "istock is experimental and must be selected explicitly"
        ),
    )
    parser.add_argument("--dry-run", action="store_true", help="List pairs without uploading")
    parser.add_argument("--force", action="store_true", help="Upload even if history marks the image complete")
    parser.add_argument(
        "--allow-unbound-metadata",
        action="store_true",
        help="Allow legacy JSON files without source_sha256 (source name is still checked)",
    )
    parser.add_argument(
        "--allow-unreviewed-metadata",
        action="store_true",
        help="Allow metadata without visual_review_status=verified",
    )
    parser.add_argument(
        "--allow-quality-warnings",
        action="store_true",
        help="Deprecated compatibility flag; keyword-count advisories never block",
    )
    parser.add_argument(
        "--allow-repeated-metadata",
        action="store_true",
        help="Allow repeated titles/descriptions after explicit review",
    )
    parser.add_argument(
        "--preserve-all-frames",
        action="store_true",
        help=(
            "Upload every explicitly requested, technically usable frame "
            "without the default three-per-burst curation limit"
        ),
    )
    parser.add_argument(
        "--repair-corrections",
        action="store_true",
        help=(
            "Repair matching Shutterstock Correction needed items using "
            "editorial metadata without uploading the files again"
        ),
    )
    args = parser.parse_args()

    if args.repair_corrections and args.platform != "shutterstock":
        parser.error("--repair-corrections requires --platform shutterstock")

    target = Path(args.directory).expanduser().resolve()

    if target.is_file():
        pairs = find_pairs(target.parent)
        pairs = [(img, jf) for img, jf in pairs if img == target]
        if not pairs:
            sys.exit(f"No JSON metadata found for: {target.name}. Run photo_desc.py first.")
    elif target.is_dir():
        pairs = find_pairs(target)
    else:
        sys.exit(f"Path does not exist: {target}")

    directory = target if target.is_dir() else target.parent
    if not pairs:
        sys.exit("No image+JSON pairs found. Run photo_desc.py first.")

    if target.is_dir() and args.preserve_all_frames and not args.repair_corrections:
        missing_metadata = find_images_without_metadata(target, pairs)
        if missing_metadata:
            names = ", ".join(path.name for path in missing_metadata)
            sys.exit(
                "Full-coverage upload blocked: "
                f"{len(missing_metadata)} image(s) have no matching metadata JSON: "
                f"{names}"
            )

    print(f"Found {len(pairs)} image(s) with metadata. Platform: {args.platform}", flush=True)
    for img, jf in pairs:
        print(f"  {img.name}  ←  {jf.name}", flush=True)

    if args.dry_run:
        print("\nDry run — no uploads performed.")
        return 0

    return 0 if run_upload(
        pairs,
        args.platform,
        force=args.force,
        allow_unbound_metadata=args.allow_unbound_metadata,
        allow_unreviewed_metadata=args.allow_unreviewed_metadata,
        allow_quality_warnings=args.allow_quality_warnings,
        allow_repeated_metadata=args.allow_repeated_metadata,
        preserve_all_frames=args.preserve_all_frames,
        repair_corrections=args.repair_corrections,
    ) else 1


if __name__ == "__main__":
    raise SystemExit(main())
