#!/usr/bin/env python3
"""
upload_photos.py — Upload stock photos to Shutterstock and/or 500px.com.cn.

For each image in the target directory, finds its matching JSON metadata file
(generated by photo_desc.py) and automates the upload via Playwright.

Usage:
  python3 upload_photos.py <directory> [--platform shutterstock|px500|all] [--dry-run]
"""

import argparse
import json
import sys
from pathlib import Path

SUPPORTED_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}


def find_pairs(directory: Path) -> list[tuple[Path, Path]]:
    """Return (image_path, json_path) pairs. For duplicate JSONs, pick the newest."""
    pairs = []
    images = {p.stem: p for p in directory.iterdir() if p.suffix.lower() in SUPPORTED_EXTS}

    json_by_stem: dict[str, list[Path]] = {}
    for jf in directory.glob("*_????????_??????.json"):
        # filename pattern: {stem}_{YYYYMMDD}_{HHMMSS}.json
        # strip the _YYYYMMDD_HHMMSS suffix to recover original stem
        parts = jf.stem.rsplit("_", 2)
        if len(parts) == 3:
            orig_stem = parts[0]
            json_by_stem.setdefault(orig_stem, []).append(jf)

    for stem, jfiles in json_by_stem.items():
        if stem not in images:
            continue
        newest_json = max(jfiles, key=lambda p: p.stat().st_mtime)
        pairs.append((images[stem], newest_json))

    return sorted(pairs, key=lambda t: t[0].name)


def load_metadata(json_path: Path) -> dict:
    return json.loads(json_path.read_text(encoding="utf-8"))


def run_upload(pairs: list[tuple[Path, Path]], platform: str) -> None:
    from playwright.sync_api import sync_playwright
    import upload.px500 as _px500
    from upload.browser import get_context

    total = len(pairs)
    results = {"ok": 0, "fail": 0}

    with sync_playwright() as pw:
        ss_ctx = get_context("shutterstock", pw) if platform in ("shutterstock", "all") else None
        px_ctx = get_context("px500", pw) if platform in ("px500", "all") else None

        try:
            # Shutterstock: batch upload all images in one file-chooser call
            if ss_ctx:
                from upload.shutterstock import upload_batch as ss_batch
                loaded = [(img, load_metadata(jf)) for img, jf in pairs]
                batch_results = ss_batch(loaded, ss_ctx)
                for ok in batch_results.values():
                    if ok:
                        results["ok"] += 1
                    else:
                        results["fail"] += 1

            # 500px: batch — select all files at once, fill metadata per draft page
            if px_ctx:
                _px500.ensure_login(px_ctx)
                loaded = [(img, load_metadata(jf)) for img, jf in pairs]
                batch_results = _px500.upload_batch(loaded, px_ctx)
                for ok in batch_results.values():
                    if ok:
                        results["ok"] += 1
                    else:
                        results["fail"] += 1
        finally:
            if ss_ctx:
                ss_ctx.close()
            if px_ctx:
                px_ctx.close()

    print(f"\nDone: {results['ok']}/{total} succeeded")
    if results["fail"]:
        print(f"Failed: {results['fail']}")


def main():
    parser = argparse.ArgumentParser(description="Upload stock photos to image platforms")
    parser.add_argument("directory", help="Directory containing images and their JSON metadata")
    parser.add_argument(
        "--platform", "-p",
        choices=["shutterstock", "px500", "all"],
        default="all",
        help="Target platform (default: all)",
    )
    parser.add_argument("--dry-run", action="store_true", help="List pairs without uploading")
    args = parser.parse_args()

    target = Path(args.directory).expanduser().resolve()

    if target.is_file():
        pairs = find_pairs(target.parent)
        pairs = [(img, jf) for img, jf in pairs if img == target]
        if not pairs:
            sys.exit(f"No JSON metadata found for: {target.name}. Run photo_desc.py first.")
    elif target.is_dir():
        pairs = find_pairs(target)
    else:
        sys.exit(f"Path does not exist: {target}")

    directory = target if target.is_dir() else target.parent
    if not pairs:
        sys.exit("No image+JSON pairs found. Run photo_desc.py first.")

    print(f"Found {len(pairs)} image(s) with metadata. Platform: {args.platform}")
    for img, jf in pairs:
        print(f"  {img.name}  ←  {jf.name}")

    if args.dry_run:
        print("\nDry run — no uploads performed.")
        return

    run_upload(pairs, args.platform)


if __name__ == "__main__":
    main()
